### ISSUE TITLE
ReadonlyMemory

### ISSUE THREAD

**Issue by SebastianStehle** [osjoberg/HtmlPerformanceKit#10]
It would be really great to have the ReadOnlyMemory endpoints in the code. As I said, I think your library is mainly used by people doing low level stuff, everybody else uses other libraries like AngleSharp.

We could also make it internal and add a static Helper to it, like:

```
Dangerously.GetNameAsMemory(reader)
```

**Comment by osjoberg** [comment]
I agree. One option that I was thinking of was having a separate `HtmlReaderMemory` or `HtmlMemoryReader` that would make it distinct from the usual `HtmlReader`. The idea would be that the same methods or properties that exisit on the `HtmlReader` would return `ReadonlyMemory` instead. There would be some duplication of code but since most of it is handled in the statemachine code that can be shared, maybe it is a viable option?

**Comment by SebastianStehle** [comment]
I would just add the methods to the default reader and make them internal and then add wrapper reader, that does not have any logic.

**Comment by SebastianStehle** [comment]
Do you have a preference? Can I provide a PR for that?

**Comment by osjoberg** [comment]
Hello,

Actually I am finalizing support for `AsMemory`. After trying different soultions and taking performance, maintenace, ease-of-use and discoverability into consideration I have landed in someting very similar as you suggested originally, additional methods and properties suffixed with  `AsMemory` to the `HtmlReader` class.

Unfortenuately as the `AsMemory` methods will be quirky to use if they are nullable and return `null` in the same manner as the old `string` counterparts do (and maybe it was an oversight to have the original properties/methods to return `null` from the beginning) I have changed the implementation both for the `string` and `ToMemory` to throw an `InvalidOperation`/`KeyNotFoundException` instead of returning `null` when being used in the wrong way.

As theese are breaking API changes I intend to change to major version1.0. I would really appreciate any feedback you have before publishing it as a package. Will probalbly sync my changes to master tomorrow.

While I am doing API changes I also decided to remove `Dispose` as I think it was a mistake to include it from the beginning.

**Comment by SebastianStehle** [comment]
Sounds good

**Comment by osjoberg** [comment]
Master is now updated with ReadOnlyMemory.

**Comment by SebastianStehle** [comment]
I like it but...

because we are talking about high performance here there is one change I would do:

Create separate methods for the "throw calls". Some exceptions already have this throw methods: https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception.throwifgreaterthanorequal?view=net-8.0

The reason is the that methods with a throw call cannot be inlined. Very often there is a "ThrowHelper" class: https://github.com/dotnet/aspnetcore/blob/main/src/Shared/ThrowHelpers/ArgumentThrowHelper.cs

**Comment by osjoberg** [comment]
I actually made an attempt to do exactly that, but I could not measure any clear performance benefit. I might have missed something...

**Comment by SebastianStehle** [comment]
Interesting. Personally I would just do it anyway, it will look familiar to other developers. but it is up to you ofc.

**Comment by osjoberg** [comment]
Relased 1.0 on nuget!

**Comment by SebastianStehle** [comment]
Awesome, thanks a lot.
