### ISSUE TITLE
Extend API: TryGetAttribute

### ISSUE THREAD

**Issue by jirisykora83** [osjoberg/HtmlPerformanceKit#2]
What do you think about adding this two API to HtmlReader?

`bool TryGetAttribute(string name, out string value)`
`bool TryGetAttribute(int id, out string value)`

Or add add HtmlReaderExtensions with this (maybe same other) helper directly to HtmlPerformanceKit?

**Comment by osjoberg** [comment]
First of all, thank you for your feedback!

The `GetAttribute` method tries to mimic the behaviour of [XmlReader.GetAttribute](https://msdn.microsoft.com/en-us/library/system.xml.xmlreader.getattribute(v=vs.110).aspx).

This means that if you know the attribute name, you can with one call can determine (by checking if the return value is null) if an attribute is set and if it is non-null, you know what value that attribute has.

However, if you try to access the attribute by an index that does not exist, you will get an `OutOfRangeException`. You can work around this by checking `AttributeCount `before calling `GetAttribute `and since the count is pre-calculated, accessing it will be quick. 

Example:
`var value =  htmlReader.AttributeCount > 3 ? htmlReader.GetAttribute(3) : null;
`

If you do this often I agree that your suggestion would be a API usability improvement, however I believe the real-world scenarios for accessing attributes by index are rare.

So to conclude, in my opinion adding, `TryGetAttribute(string name, out string value)` would basically duplicate the existing implementation. ` TryGetAttribute(int id, out string value)` would make more sense, however the use-cases are few.

What benefits do you see with adding the TryGetAttribute implementations?

**Comment by jirisykora83** [comment]
Sorry for late response.

Yes you have right access by index is probably rare actually i don't use it. It was wrong suggestion i don't think about it to much.

Back to `TryGetAttribute(string name, out string value)` i believe checking if the accessing attribute exist is really common scenario for example first example here on github:

```
while (htmlReader.Read())
{
	if (htmlReader.TokenKind == HtmlTokenKind.Tag && htmlReader.Name == "a")
	{
		var hrefAttributeValue = htmlReader.GetAttribute("href");
		if (hrefAttributeValue != null)
		{
			yield return hrefAttributeValue;
		}
	}
}
```
 
Can be:

```
while (htmlReader.Read())
{
	if (htmlReader.TokenKind == HtmlTokenKind.Tag && htmlReader.Name == "a" 
	    && htmlReader.TryGetAttribute("href", string hrefAttributeValue))
	{
		yield return hrefAttributeValue;
	}
}
```

And this is simple scenario. But when for example you want to check if class is something and then check if href not empty. You can do this:

```
while (htmlReader.Read())
{
	if (htmlReader.TokenKind == HtmlTokenKind.Tag && htmlReader.Name == "a")
	{
		var classValue = htmlReader.GetAttribute("class");
		if (classValue == "class-what-i-want")
		{
			var hrefValue = htmlReader.GetAttribute("href");
			if (hrefValue != null)
			{
				yield return hrefAttributeValue;
			}
		}
	}
}
```
Of course you can get `classValue` & `hrefValue` a then check it in one `if` but then you waste some CPU time to getting href attribute for every a token even if you don't need it.

Or you can write something like this:

```
while (htmlReader.Read())
{
	if (htmlReader.TokenKind == HtmlTokenKind.Tag && htmlReader.Name == "a"
	    && htmlReader.TryGetAttribute("class", string classValue) && classValue == "class-what-i-want"
	    && htmlReader.TryGetAttribute("href", string hrefValue))
	{
		yield return hrefAttr;
	}
}

```

**Summary**: Of course you have right. Implementation do not add anything what could not be achive with currently API. But main benefit of this is increase readability in common case (at least from my point of view).

And also it can be interesting add overload method with `StringComparison`  to `GetAttribute` and potentially `TryGetAttribute` methods. At least when i check it last time it will be faster use `Equals` with `StringComparison.OrdinalIgnoreCase` instant of `==`.

**Comment by osjoberg** [comment]
Thanks for the clarification! As I don´t have much time to spare on this project at the moment, feel free to submit a patch if you want this feature. My only requirement to include it, is that the performance must be close or better than the existing GetAttribute implementation since this in my usage the most called method in the library.

**Comment by jirisykora83** [comment]
Sorry i am supper bursy last month, but now i finally have some time.

Also i have idea how improve performance slightly. If GetAttribute / TryGetAttribute also get parameter with StringComparison. Base on this article it look like you can get some extra performance (i dont run profiler yet).

http://pmichaels.net/2017/06/04/using-benchmarkdotnet-profile-string-comparison/

And in dotnet git repository is often put exceptional path to seperte method. Because at least if i understand correctly when you have throw exception in method its prevent to be inlined). 

Also some method in typical hot path could be mark as AggressiveInlining?

**Comment by SebastianStehle** [comment]
I would just close that.
