### ISSUE TITLE
Greetings from the author of HtmlKit

### ISSUE THREAD

**Issue by jstedfast** [osjoberg/HtmlPerformanceKit#4]
Hey, I just found this. Good job at beating HtmlKit ;-)

I'm a bit curious as to how your library is getting such good performance compared to HtmlKit seeing as how they are both very similar (being that we both more-or-less implemented the state machine described in HTML5's tokenization docs).

A few thoughts so far:

1. HtmlKit decodes character references in both data and attribute values whereas HtmlPerformanceKit does not. HtmlKit's HtmlTokenizer *does* have a `DecodeCharacterReferences` property which disables decoding of character references in data, but not in attribute values. I modified your benchmarking code to set `DecodeCharacterReferences` to `false` and that did not seem to improve performance for HtmlKit by much at all, unfortunately. That said, that still leaves character reference decoding of attribute values. Glancing at your test input, there doesn't appear to be a huge number of character references anyway, so this difference might not really be the culprit... at least not for the sample input used by the benchmark.
2. Your tokenizer pre-sizes the tag name (100), comment (10K), and data buffers (10K) whereas HtmlKit does not. You also have custom buffers where HtmlKit just uses `StringBuilder`. I don't know what `StringBuilder` defaults its initial capacity to, but I'm guessing ~256 chars so our name buffers are probably comparable (in that neither one likely needs to be resized for the most common inputs and certainly not for your test input), but using as 10K initial capacity buffer for data/comments/etc means HtmlPerformanceKit never needs to resize its buffers whereas I guarantee that HtmlKit *does* need to. Perhaps I should consider setting an initial capacity to 2-4K (I think 10K is probably overkill tbh). Not sure how much this affects the performance.
3. Aggressive inlining of, well, nearly everything. HtmlKit doesn't inline anything at all. I'm curious how much of an impact your aggressive inlining really has. Have you done any tests to see the before/after?

Do you have any other thoughts on why your tokenizer is faster? Just curious if you've poked around to answer this question yourself.

I might have to spend some time digging around at some point to figure this out.

**Comment by osjoberg** [comment]
Hello!

Nice to hear from you, and congratulations to you for having a great library! If I had found your library from the beginning I would never have written mine. :)

Without having the time to go thought the sources I don't really know what the difference in performance could be, however I have spent quite some time profiling/benchmarking the code and made changes to make sure thing run as fast as possible.

1. I do not think it makes such a big difference in performance, as long as your input have a lot of character references. If  I recall correctly, it is basically only one comparison extra per character read "wasted" to determine if there is a character reference or not and resolving a character reference when it occurs is simply a dictionary lookup. 

2. The sizing is more aligned with expected input from parsing HTML documents than the .NET defaults to reduce memory pressure and reduce resizing and in turn reduce GC collections. This should not affect simple benchmarks.

3. Aggressive inlining plays a part, however it does not explain the whole difference in performance. All inlinings are made after careful profiling/benchmarking.

I think most gains during development where made by avoiding using the string type when possible and trying to avoid any excess code. My custom replacement for StringBuilder for example does not do null checks on input arguments to save a couple of instructions and also since it does not throw an exception on null may make it more likely to be inlined.

There are probably more things to do to improve the performance
- Less use of strings
- Use spans instead of strings in string operations and when reading from the input buffer
- "Lazy" decoding of tokens so that for example attributes are not decoded before the caller tries to access them

However at this stage I don't have the time to continue with this project.

Glad you reached out!

Best regards,
Oskar

**Comment by jstedfast** [comment]
Yea, I was also feeling that the inlining would probably not explain the difference between HtmlKit and HtmlPerformanceKit. Those types of optimizations, in my experience, shave off minuscule amounts of time.

Since my comment above, I looked up what the default capacity was for StringBuilder and it wasn't 256 like I had assumed, it was only [16](https://referencesource.microsoft.com/#mscorlib/system/text/stringbuilder.cs,67).

Interestingly, StringBuilder is also a linked-list of max 8000-character buffers.

HtmlKit was only meant to provide basic HTML processing support for [MimeKit](https://github.com/jstedfast/MimeKit) for things like manipulating `<img src=...>` tags to load content from a a file system location when the original src value was a `cid:...` value and such, so it serves that purpose well.

That said, I might have to look into seeing if I can improve performance a bit more, knowing that I could realistically double its speed.

As your benchmarks show, other than HtmlPerformanceKit, HtmlKit is significantly faster than everything else and having done my own sort of tests, I hadn't bothered to spend any more time on optimizing it further.

Truth be told, I haven't spent *any* time optimizing it - I essentially just implemented the state machine as described by the specs and when that turned out to be faster than the other HTML parsers (in all fairness, they do more, as you also noted in your README), I was content to move on.

Anyway, I'll try to let you know how I make out when I get around to digging into this more.

**Comment by jstedfast** [comment]
Managed to optimize HtmlKit a bit more...

```
              Method |     Mean |     Error |    StdDev |
-------------------- |---------:|----------:|----------:|
        ExtractLinks | 21.24 ms | 0.4158 ms | 0.7707 ms |
 ExtractLinksHtmlKit | 26.31 ms | 0.4397 ms | 0.4113 ms |
        ExtractTexts | 27.28 ms | 0.2122 ms | 0.1881 ms |
 ExtractTextsHtmlKit | 33.54 ms | 0.3469 ms | 0.2897 ms |
```

A pretty huge hunk of that improvement (~90% of the overall improvement) was due to [OptimizedOrdinalIgnoreCaseComparer](https://github.com/jstedfast/HtmlKit/blob/master/HtmlKit/OptimizedOrdinalComparer.cs).

I also ended up implementing my own CharBuffer much like you did, altho mine is a bit simpler than yours. That accounted for a small (~8-9% of the overall improvement), but still significant, chunk of improvement.

And then I also implemented faster versions of some utility functions in the tokenizer such as IsAlphaNumeric(), IsAsciiLetter() and ToLower(): https://github.com/jstedfast/HtmlKit/blob/master/HtmlKit/HtmlTokenizer.cs#L234

These newer utility functions were ~2x faster than what I was using before, but they made fairly insignificant improvements overall in the benchmark results due to their minimal usage on the code.

Essentially, what I discovered is that nearly all of the performance differences between HtmlKit and HtmlPerformanceKit was due to the fact that HtmlKit maps tag names and attribute names to enum values whereas HtmlPerformanceKit is content to just use the string value.

In order to eliminate that last bit of difference, getting rid of the string -> enum mapping is more-or-less all that would be needed. Possibly a bad design decision on my part, but it's there and it can be nice to use enums if you want to do a lot of comparisons using the tag/attribute name/id.
